server:
  port: 8889
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
      
spring:
  application:
    name: App-gateway
  cloud:
    gateway:
      routes:
      - id: bank
        uri: lb://bank-service
        predicates:
        - Path=/bank/**
      - id: gpay
        uri: lb://gpay-service
        predicates:
        - Path=/gpay/**